ingress-nginx:
  controller:
    kind: DaemonSet
    hostNetwork: true
    service:
      type: LoadBalancer
      # externalTrafficPolicy: Cluster
      httpPort.enable: true
      httpPort.port: 80
      httpsPort.enable: true
      httpsPort.port: 443
    admissionWebhooks:
      timeoutSeconds: 30
    # metrics:
    #   enabled: true
    #   serviceMonitor:
    #     enabled: true
  # tcp:
  #   22: gitea/gitea-ssh:22
